version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: protobuf
    versions:
    - 3.14.0
    - 3.15.0
    - 3.15.1
    - 3.15.2
    - 3.15.3
    - 3.15.4
    - 3.15.5
    - 3.15.6
    - 3.15.7
  - dependency-name: scipy
    versions:
    - 1.6.0
    - 1.6.1
    - 1.6.2
  - dependency-name: h5py
    versions:
    - 3.1.0
    - 3.2.0
  - dependency-name: numpy
    versions:
    - 1.19.5
    - 1.20.0
  - dependency-name: pyyaml
    versions:
    - "5.1"
  - dependency-name: jinja2
    versions:
    - 2.10.1
